export const LOADING_DATA = "LOADING_DATA";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CART_ITEM = "SET_CART_ITEM";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
